import Provider from "../components/Provider";
import "./globals.css";

export const metadata = {
  title: "Next CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
